{
 "title": "New dashboard",
 "time": { "from": "2025-02-16T08:30:23.895Z", "to": "2025-02-16T08:40:23.895Z" },
 "panels": [
  {
   "title": "Raw Data",
   "type": "xychart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    wave_id,\n    floor(rel_time/1/1E6) * 1 *1E6 AS time_bucket,\n    avg(value) AS avg_value,\n    count() AS samples\nFROM raw_data\nGROUP BY wave_id, time_bucket\nORDER BY wave_id, time_bucket"
    }
   ]
  },
  {
   "title": "Decimated (Avg of 1/10 points)",
   "type": "xychart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n    wave_id,\n    floor(rel_time/10/1E6) * 10 *1E6 AS time_bucket,\n    avg(value) AS avg_value,\n    count() AS samples\nFROM raw_data\nGROUP BY wave_id, time_bucket\nORDER BY wave_id, time_bucket"
    }
   ]
  },
  {
   "title": "Min/Max Downsampling Method",
   "type": "xychart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\n    wave_id,\n    floor(rel_time/1/1E6) * 1 *1E6 AS time_bucket,\n    avg(value) AS avg_value,\n    count() AS samples\nFROM processed_data\nGROUP BY wave_id, time_bucket\nORDER BY wave_id, time_bucket"
    }
   ]
  }
 ]
}